version: '4.4.3'

services:
  memesis-app-frontend:
    container_name: memesis-app-frontend
    build:
      context: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules: